name: kobkiat_it_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  injectable: ^2.3.5
  injectable_generator: ^2.4.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
